### ISSUE TITLE
Add https://lightningshop.eu/

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#19]
Add https://lightningshop.eu/ to http://lightningnetworkstores.com/

**Comment by lightningnetworkstores** [comment]
Hi, by default the website doesn't show all stores because going forward it would cause the webpage to be too long. If you click "size: big" and change it to "size: all" you will see it, it has been there for a while :)

I might put a warning in the future that not all stores are shown by default... please tell me what you think. The website is ranked as #16MM worldwide (https://www.alexa.com/siteinfo/lightningshop.eu), so I set it to "small".

**Comment by bitcoinuser** [comment]
Now I understand. Thanks.
