### ISSUE TITLE
Incorrect Wallet

### ISSUE THREAD

**Issue by ekerstein** [lightningnetworkstores/lightningnetworkstores.github.io#41]
I just downloaded this "iOS testnet wallet". It is not a lightning wallet at all. I believe this is spam. Please delete it from the list:

https://github.com/lightningnetworkstores/lightningnetworkstores.github.io/blob/59435a1f287b5267b29c420c02329a7a21cb58a3/wallets.json#L43

**Comment by lightningnetworkstores** [comment]
It was there because they announced they would integrate lightning in the future: https://www.reddit.com/r/Bitcoin/comments/8ln7om/bitcoin_lightning_payment_by_cipherbook_app/

As this has caused confusion I will remove the link. I (or some PR) will add some more columns to the wallets table in the future and maybe add back the link later then.

**Comment by lightningnetworkstores** [comment]
Solved. Thanks one more time!
