### ISSUE TITLE
Add https://gullyflip.com

### ISSUE THREAD

**Issue by bitcoinuser** [lightningnetworkstores/lightningnetworkstores.github.io#89]
Add https://gullyflip.com

Obs. They use globee.com payment processor. I tested it and it has lightning payment option.

Why you are not adding the sites i'm posting here in github?

**Comment by pedro-roberto** [comment]
Hey, sorry for the delay. I have been working on a new automatic way to add stores to the website and therefore I am keeping some stores for "test". The main reason is lack of time though, it's easier to add them when people make pull requests. Next weekend they will be added for sure. Also, would like to speak to you in private because I would like to give you a password that lets you add stores without paying (I will charge a very small amount to add stores, mostly to prevent spam).

**Comment by pedro-roberto** [comment]
Please send an email to lightningnetworkstores@gmail.com

**Comment by pedro-roberto** [comment]
This website was added, I wait for your answer on my mailbox @bitcoinuser
